- hosts: localhost
  connection: local
  become: false # Don't use sudo for this part
  vars:
    region: us-west-2 #ap-southeast-2
  tasks:
    - name: Gather EC2 facts
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:Type": "clientsites"
      register: ec2
    - debug: var=ec2

    - name: Download our URL checking script
      get_url:
        url=https://raw.githubusercontent.com/mitchelljdavies/2018_Group_1/Task_3/checkurl.sh
        dest=/var/www/html/

    - name: Make sure it's executable
      file:
        path: /var/www/html/checkurl.sh
        owner: ec2-user
        group: apache
        mode: 0777

    - name: Checking instance's homepage URL to confirm it is live...
      command: /var/www/html/./checkurl.sh "{{ item.public_ip_address }}"
      with_items: "{{ ec2.instances }}"
      register: checkurl
    - debug: var=checkurl
