---
- hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Send an email
      mail: 
        host: localhost
        port: 25
        to: Firstname Lastname <email@email.com>
        subject: Ansible
        body: Testing Ansible email