---
- name: "Install updates/PHP/Apache/MariaDB"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: install package updates
      yum:
        name: '*'
        state: latest

    - name: install PHP
      shell: amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2

    - name: install Apache and MariaDB
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - mariadb-server

- name: "Start and enable Apache"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: yes

- name: "Set permissions"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Add ourself to Apache group
      user:
        name: ec2-user
        groups: apache
        append: yes


    - name: Give apache group ownership of /var/www and add permissions
      file:
        path: /var/www
        owner: ec2-user
        group: apache
        mode: 02775
        recurse: yes

    - name: Add group write permissions to /var/www
      command: find /var/www -type f -exec sudo chmod 0664 {} \;

- name: "Start DB server"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

#- name: "Secure DB server"
 # We may need to replicate mysql_secure_installation here, rather than passing a command to the shell.
 # See https://stackoverflow.com/questions/25136498/ansible-answers-to-mysql-secure-installation#25140114

- name: "Install WordPress"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Install WordPress through CLI
      shell: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar # Download the WP CLI
        chmod +x wp-cli.phar # Make the WP CLI executable
        sudo mv wp-cli.phar /usr/local/bin/wp # Put it in our PATH so we can just call "wp"
        cd /var/www/html # Navigate to our html directory
        wp core download # Download WordPress Core
        wp core config --dbname=wp-db --dbuser=root --dbpass=test # Generate our config file
        wp db create # Create the database for our WordPress site
        IP=$(curl http://169.254.169.254/latest/meta-data/public-ipv4) # Get the server's public IP
        wp core install --url="http://$IP" --title="Assignment 1 WordPress Site" --admin_user="group_1" --admin_password="alpha wario salamander" --admin_email="test@test.co.nz" # Install WordPress and set up our user
     
