---
- name: "Install updates/PHP/Apache/MariaDB"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: install package updates
      yum:
        name: '*'
        state: latest

    - name: install PHP
      shell: amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2

    - name: install Apache and MariaDB
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - mariadb-server
        - MySQL-python

- name: "Start and enable Apache"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: yes

- name: "Set permissions"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Add ourself to Apache group
      user:
        name: ec2-user
        groups: apache
        append: yes


    - name: Give apache group ownership of /var/www and add permissions
      file:
        path: /var/www
        owner: ec2-user
        group: apache
        mode: 02775
        recurse: yes

    - name: Add group write permissions to /var/www
      command: find /var/www -type f -exec sudo chmod 0664 {} \;

- name: "Start DB server"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

#- name: "Secure DB server"
 # We may need to replicate mysql_secure_installation here, rather than passing a command to the shell.
 # See https://stackoverflow.com/questions/25136498/ansible-answers-to-mysql-secure-installation#25140114

- name: "Install WordPress"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Download pexpect
      shell: sudo pip install pexpect

    - name: Download WordPress CLI
      shell: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

    - name: Make the CLI executable
      shell: chmod +x wp-cli.phar

    - name: Put the CLI in PATH
      shell: sudo mv wp-cli.phar /usr/local/bin/wp

    - name: Navigate to html directory
      shell: cd /var/www/html

    - name: Download WordPress core
      shell: /usr/local/bin/wp core download

    - name: Generate wp-config file
      shell: /usr/local/bin/wp config create --dbname=wp-db --dbuser=root --dbpass=test 

    - name: Create the database for the WordPress site
      shell: /usr/local/bin/wp db create 

    - name: Get the server's public IP
      shell: IP=$(curl http://169.254.169.254/latest/meta-data/public-ipv4) 

    - name: Install WordPress and set up the user
      shell: /usr/local/bin/wp core install --url="http://$IP" --title="Assignment 1 WordPress Site" --admin_user="group_1" --admin_password="alpha wario salamander" --admin_email="test@test.co.nz"
     
