---
- name: Check that an instance is running
  hosts: localhost
  connection: local
  become: False
  #vars: #Add variables here
  tasks:
    - name: Set up an alarm
      ec2_metric_alarm:
        name: "status-check"
        state: present
        region: us-west-2
        metric: "StatusCheckFailed"
        namespace: "AWS/EC2"
        statistic: Average
        comparison: ">="
        threshold: 1 
        period: 900 # 15 minute evaluation period
        evaluation_periods: 1 # triggers the alarm if the average number of failures in one 15-minute period is more than 1
        dimensions: {'InstanceId':'i-01b42266c128e122b'} # What the alarm is applied to
        # alarm_actions: # What happens when the alarm is in 'alarm' status