- name: Create a sandbox instance
  hosts: localhost
  connection: local
  become: false # Don't use sudo
  gather_facts: False
  vars:
    key_name: MyKeyPair # This will have to be your own key I think
    instance_type: t2.micro
    security_group: my-security-group
    image: ami-39f8215b
    region: ap-southeast-2
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         user_data: "curl -s https://raw.githubusercontent.com/mitchelljdavies/2018_Group_1/master/task_1.sh | bash"
         assign_public_ip: yes
      register: ec2
