- name: Create a sandbox instance
  hosts: localhost
  connection: local
  become: false # Don't use sudo
  gather_facts: False
  vars:
    instance_type: t2.micro
    security_group: my-security-group
    image: ami-39f8215b
    region: ap-southeast-2
  tasks:
    - name: Launch instance
      ec2:
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
      register: ec2
